routes/web.php
<?php

use App\Http\Controllers\Admin\CareerController as AdminCareerController;
use App\Http\Controllers\Admin\Content\AboutController;
use App\Http\Controllers\Admin\Content\HomeController;
use App\Http\Controllers\Admin\Content\SolutionController as ContentSolutionController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Home\HomepageController;
use App\Http\Controllers\Home\TechnologyController;
use App\Http\Controllers\Home\CareerController;
use App\Http\Controllers\Home\SolutionController;
use App\Http\Controllers\Home\NewsController;
use App\Http\Controllers\Home\AboutUsController;
use App\Http\Controllers\Home\ServicesController;

use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\NewsController as AdminNewsController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;

Route::get('/', [HomepageController::class, 'index'])->name('homepage');
Route::get('/lang/id', function () {
    Session::put('locale', 'id');
    App::setLocale('id');
    return back();
})->name('lang-id');

Route::get('/lang/en', function () {
    Session::put('locale', 'en');
    return back();
})->name('lang-en');

Route::get('/home/{id}', [HomepageController::class, 'show'])->name('homepage-show');
Route::post('/login', [LoginController::class, 'login'])->name('login-attempt');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

Route::get('/technology', [TechnologyController::class, 'index'])->name('tech-index');

Route::get('/aboutus', [AboutUsController::class, 'index'])->name('aboutus-index');

Route::get('/career', [CareerController::class, 'index'])->name('career-index');
Route::get('/career/{id}', [CareerController::class, 'show'])->name('career-show');

Route::get('/news', [NewsController::class, 'index'])->name('news-index');
Route::get('/news/{id}', [NewsController::class, 'show'])->name('news-show');

Route::get('/solution', [SolutionController::class, 'index'])->name('solution-index');

Route::get('/services', [ServicesController::class, 'index'])->name('services-index');

Route::get('/login', [LoginController::class, 'index'])->name('login-index');

Route::get('/dashboard', function () {
    return view('layouts.dashboard');
});


//admin
Route::prefix('/admin')->name('admin.')->middleware(['isUser'])->group(function () {
    Route::get(
        '/dashboard',
        function () {
            return view('pages.admin.dashboard');
        }
    )->name('dashboard');

    Route::prefix('/users')->name('users.')->group(
        function () {
            Route::get('/', [UserController::class, 'index'])->name('index');
            Route::post('/store', [UserController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [UserController::class, 'edit'])->name('edit');
            Route::post('/update', [UserController::class, 'update'])->name('update');
            Route::post('/action', [UserController::class, 'action'])->name('action');
        }
    );

    Route::prefix('/careers')->name('careers.')->group(
        function () {
            Route::get('/', [AdminCareerController::class, 'index'])->name('index');
            Route::post('/store', [AdminCareerController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [AdminCareerController::class, 'edit'])->name('edit');
            Route::post('/update', [AdminCareerController::class, 'update'])->name('update');
            Route::post('/action', [AdminCareerController::class, 'action'])->name('action');
        }
    );

    Route::prefix('/news')->name('news.')->group(
        function () {
            Route::get('/', [AdminNewsController::class, 'index'])->name('index');
            Route::post('/store', [AdminNewsController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [AdminNewsController::class, 'edit'])->name('edit');
            Route::post('/update', [AdminNewsController::class, 'update'])->name('update');
            Route::post('/action', [AdminNewsController::class, 'action'])->name('action');
        }
    );

    Route::prefix('/content')->name('content.')->group(
        function () {
            Route::prefix('/home')->name('home.')->group(
                function () {
                    Route::get('/', [HomeController::class, 'index'])->name('index');
                    Route::get('/edit/{id}', [HomeController::class, 'edit'])->name('edit');
                    Route::post('/update', [HomeController::class, 'update'])->name('update');
                }
            );
            Route::prefix('/about-us')->name('about.')->group(
                function () {
                    Route::get('/', [AboutController::class, 'index'])->name('index');
                    Route::get('/edit/{id}', [AboutController::class, 'edit'])->name('edit');
                    Route::post('/update', [AboutController::class, 'update'])->name('update');
                }
            );
            Route::prefix('/solution')->name('solution.')->group(
                function () {
                    Route::get('/', [ContentSolutionController::class, 'index'])->name('index');
                    Route::get('/edit/{id}', [ContentSolutionController::class, 'edit'])->name('edit');
                    Route::post('/update', [ContentSolutionController::class, 'update'])->name('update');
                }
            );
        }
    );
});

resources/views/layouts/dashboard/sidebar.blade.php
@extends('header')

@section('sidebar')
    
@endsection

resources/views/layouts/dashboard/template.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @yield('title')

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href={{ asset('dist/font/font.css') }}>
    <!-- Sweet Alert -->
    <link rel="stylesheet" href={{ asset('plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') }}>
    <!-- Font Awesome -->
    <link rel="stylesheet" href={{ asset('plugins/fontawesome-free/css/all.min.css') }}>
    <!-- Ionicons -->
    <link rel="stylesheet" href={{ asset('dist/css/ionicons.min.css') }}>
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href={{ asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}>
    <!-- iCheck -->
    <link rel="stylesheet" href={{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}>
    <!-- JQVMap -->
    <link rel="stylesheet" href={{ asset('plugins/jqvmap/jqvmap.min.css') }}>
    <!-- Theme style -->
    <link rel="stylesheet" href={{ asset('dist/css/adminlte.min.css') }}>
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href={{ asset('plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}>
    <!-- Daterange picker -->
    <link rel="stylesheet" href={{ asset('plugins/daterangepicker/daterangepicker.css') }}>
    <!-- summernote -->
    <link rel="stylesheet" href={{ asset('plugins/summernote/summernote-bs4.min.css') }}>
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src={{ asset('assets/roatex.png') }} alt="AdminLTELogo">
        </div>

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i
                            class="fas fa-bars"></i></a>
                </li>
            </ul>
            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('logout') }}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
            </ul>
        </nav>

        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="#" class="brand-link">
                <img src="{{ asset('assets/roatex.png') }}" alt="AdminLTE Logo" class="brand-image"
                    style="opacity: .8">
                <span class="brand-text font-weight-light">Admin</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="{{ asset('assets/user.png') }}" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">{{ Auth::user()->name }}</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <li class="nav-item {{ request()->is('admin/content/*') ? 'menu-open' : '' }}">
                            <a href="#" class="nav-link {{ request()->is('admin/content/*') ? 'active' : '' }}">
                                <i class="nav-icon fas fa-tags"></i>
                                <p>
                                    Content
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{{ route('admin.content.home.index') }}"
                                        class="nav-link {{ request()->is('admin/content/home*') ? 'active' : '' }}">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Home</p>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{{ route('admin.content.about.index') }}"
                                        class="nav-link {{ request()->is('admin/content/about*') ? 'active' : '' }}">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>About Us</p>
                                    </a>
                                </li>
                            </ul>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{{ route('admin.content.solution.index') }}"
                                        class="nav-link {{ request()->is('admin/content/solution*') ? 'active' : '' }}">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Solution</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.news.index') }}"
                                class="nav-link {{ request()->is('admin/news*') ? 'active' : '' }}">
                                <i class="nav-icon fas fa-newspaper"></i>
                                <p>
                                    News
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.careers.index') }}"
                                class="nav-link {{ request()->is('admin/career*') ? 'active' : '' }}">
                                <i class="nav-icon fas fa-business-time"></i>
                                <p>
                                    Career
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.users.index') }}"
                                class="nav-link {{ request()->is('admin/users*') ? 'active' : '' }}">
                                <i class="nav-icon fas fa-user-alt"></i>
                                <p>Users</p>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>

        @yield('content')

        <footer class="main-footer">
            <strong>Copyright &copy; 2021 <a href="#">PT. Roatex Indonesia Toll System</a>.</strong>
            All rights reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    <!-- jQuery -->
    <script src={{ asset('plugins/jquery/jquery.min.js') }}></script>
    <!-- jQuery UI 1.11.4 -->
    <script src={{ asset('plugins/jquery-ui/jquery-ui.min.js') }}></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src={{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}></script>
    <!-- ChartJS -->
    <script src={{ asset('plugins/chart.js/Chart.min.js') }}></script>
    <!-- Sparkline -->
    <script src={{ asset('plugins/sparklines/sparkline.js') }}></script>
    <!-- JQVMap -->
    <script src={{ asset('plugins/jqvmap/jquery.vmap.min.js') }}></script>
    <script src={{ asset('plugins/jqvmap/maps/jquery.vmap.usa.js') }}></script>
    <!-- jQuery Knob Chart -->
    <script src={{ asset('plugins/jquery-knob/jquery.knob.min.js') }}></script>
    <!-- daterangepicker -->
    <script src={{ asset('plugins/moment/moment.min.js') }}></script>
    <script src={{ asset('plugins/daterangepicker/daterangepicker.js') }}></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src={{ asset('plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}></script>
    <!-- Summernote -->
    <script src={{ asset('plugins/summernote/summernote-bs4.min.js') }}></script>
    <!-- overlayScrollbars -->
    <script src={{ asset('plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}></script>
    <!-- AdminLTE App -->
    <script src={{ asset('dist/js/adminlte.js') }}></script>
    <!-- Sweet Alert -->
    {{-- <script src={{ asset('dist/js/sweetalert2.min.js') }}></script> --}}
    {{-- <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script> --}}
    <script src={{ asset('plugins/sweetalert2/sweetalert2.min.js') }}></script>
    <!-- AdminLTE for demo purposes -->
    <script src={{ asset('dist/js/script.js') }}></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src={{ asset('dist/js/pages/dashboard.js') }}></script>
</body>

</html>