routes/web.php
<?php

use App\Http\Controllers\Admin\CareerController as AdminCareerController;
use App\Http\Controllers\Admin\Content\AboutController;
use App\Http\Controllers\Admin\Content\HomeController;
use App\Http\Controllers\Admin\Content\SolutionController as ContentSolutionController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Home\HomepageController;
use App\Http\Controllers\Home\TechnologyController;
use App\Http\Controllers\Home\CareerController;
use App\Http\Controllers\Home\SolutionController;
use App\Http\Controllers\Home\NewsController;
use App\Http\Controllers\Home\AboutUsController;
use App\Http\Controllers\Home\ServicesController;

use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\NewsController as AdminNewsController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;

Route::get('/', [HomepageController::class, 'index'])->name('homepage');
Route::get('/lang/id', function () {
    Session::put('locale', 'id');
    App::setLocale('id');
    return back();
})->name('lang-id');

Route::get('/lang/en', function () {
    Session::put('locale', 'en');
    return back();
})->name('lang-en');

Route::get('/home/{id}', [HomepageController::class, 'show'])->name('homepage-show');
Route::post('/login', [LoginController::class, 'login'])->name('login-attempt');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

Route::get('/technology', [TechnologyController::class, 'index'])->name('tech-index');

Route::get('/aboutus', [AboutUsController::class, 'index'])->name('aboutus-index');

Route::get('/career', [CareerController::class, 'index'])->name('career-index');
Route::get('/career/{id}', [CareerController::class, 'show'])->name('career-show');

Route::get('/news', [NewsController::class, 'index'])->name('news-index');
Route::get('/news/{id}', [NewsController::class, 'show'])->name('news-show');

Route::get('/solution', [SolutionController::class, 'index'])->name('solution-index');

Route::get('/services', [ServicesController::class, 'index'])->name('services-index');

Route::get('/login', [LoginController::class, 'index'])->name('login-index');

Route::get('/dashboard', function () {
    return view('layouts.dashboard');
});


//admin
Route::prefix('/admin')->name('admin.')->middleware(['isUser'])->group(function () {
    Route::get(
        '/dashboard',
        function () {
            return view('pages.admin.dashboard');
        }
    )->name('dashboard');

    Route::prefix('/users')->name('users.')->group(
        function () {
            Route::get('/', [UserController::class, 'index'])->name('index');
            Route::post('/store', [UserController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [UserController::class, 'edit'])->name('edit');
            Route::post('/update', [UserController::class, 'update'])->name('update');
            Route::post('/action', [UserController::class, 'action'])->name('action');
        }
    );

    Route::prefix('/careers')->name('careers.')->group(
        function () {
            Route::get('/', [AdminCareerController::class, 'index'])->name('index');
            Route::post('/store', [AdminCareerController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [AdminCareerController::class, 'edit'])->name('edit');
            Route::post('/update', [AdminCareerController::class, 'update'])->name('update');
            Route::post('/action', [AdminCareerController::class, 'action'])->name('action');
        }
    );

    Route::prefix('/news')->name('news.')->group(
        function () {
            Route::get('/', [AdminNewsController::class, 'index'])->name('index');
            Route::post('/store', [AdminNewsController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [AdminNewsController::class, 'edit'])->name('edit');
            Route::post('/update', [AdminNewsController::class, 'update'])->name('update');
            Route::post('/action', [AdminNewsController::class, 'action'])->name('action');
        }
    );

    Route::prefix('/content')->name('content.')->group(
        function () {
            Route::prefix('/home')->name('home.')->group(
                function () {
                    Route::get('/', [HomeController::class, 'index'])->name('index');
                    Route::get('/edit/{id}', [HomeController::class, 'edit'])->name('edit');
                    Route::post('/update', [HomeController::class, 'update'])->name('update');
                }
            );
            Route::prefix('/about-us')->name('about.')->group(
                function () {
                    Route::get('/', [AboutController::class, 'index'])->name('index');
                    Route::get('/edit/{id}', [AboutController::class, 'edit'])->name('edit');
                    Route::post('/update', [AboutController::class, 'update'])->name('update');
                }
            );
            Route::prefix('/solution')->name('solution.')->group(
                function () {
                    Route::get('/', [ContentSolutionController::class, 'index'])->name('index');
                    Route::get('/edit/{id}', [ContentSolutionController::class, 'edit'])->name('edit');
                    Route::post('/update', [ContentSolutionController::class, 'update'])->name('update');
                }
            );
        }
    );
});

app/Models/Career.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Career extends Model
{
    use HasFactory;

    protected $table = 'career';

    protected $primaryKey = 'id';

    protected $fillable = [
        'department',
        'title',
        'desc',
        'department_ind',
        'title_ind',
        'desc_ind',
        'is_deleted',
        'user'
    ];
}

app/Http/Controllers/Admin/CareerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Career;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class CareerController extends Controller
{
    public function index()
    {
        $data = Career::orderBy('created_at', 'desc')->get();
        return view('pages.admin.career.index', compact('data'));
    }
    public function store(Request $request)
    {
        $data = Validator::make(
            $request->all(),
            [
                'department' => ['required', 'string'],
                'department_ind' => ['required', 'string'],
                'title' => ['required', 'string'],
                'title_ind' => ['required', 'string'],
                'desc' => ['required', 'string'],
                'desc_ind' => ['required', 'string'],
                'status' => ['required'],
            ]
        );

        if ($data->fails()) {
            $result = array('status' => 'failed', 'errors' => $data->errors());
        } else {
            Career::create([
                'department' => $request->department,
                'department_ind' => $request->department_ind,
                'title' => $request->title,
                'title_ind' => $request->title_ind,
                'desc' => $request->desc,
                'desc_ind' => $request->desc_ind,
                'user_inserted' => Auth::user()->name,
                'is_active' => $request->status,
            ]);
            $result = array('status' => 'success');
        }
        echo json_encode($result);
    }

    public function edit(Request $request, $id)
    {
        $data = Career::find($id);
        return view('pages.admin.career.edit', compact('data'));
    }

    public function update(Request $request)
    {
        $data = Validator::make(
            $request->all(),
            [
                'department' => ['required', 'string'],
                'department_ind' => ['required', 'string'],
                'title' => ['required', 'string'],
                'title_ind' => ['required', 'string'],
                'desc' => ['required', 'string'],
                'desc_ind' => ['required', 'string'],
                'status' => ['required'],
            ]
        );

        if ($data->fails()) {
            $result = array('status' => 'failed', 'errors' => $data->errors());
        } else {
            $career = Career::find($request->id);
            $career->update([
                'department' => $request->department,
                'department_ind' => $request->department_ind,
                'title' => $request->title,
                'title_ind' => $request->title_ind,
                'desc' => $request->desc,
                'desc_ind' => $request->desc_ind,
                'is_deleted' => $request->status,
            ]);
            $result = array('status' => 'success');
        }
        echo json_encode($result);
    }

    public function action(Request $request)
    {
        $data = Career::find($request->id);
        $data->is_deleted = intval($request->action);
        $data->save();
        $result = array('status' => 'success', 'data' => $data);
        echo json_encode($result);
    }
}

app/Http/Controllers/Home/CareerController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Controllers\Controller;
use App\Models\Career;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;

class CareerController extends Controller
{
    public function index()
    {
        if (Session::get('locale') == "") {
            Session::put('locale', 'en');
        }
        App::setLocale(Session::get('locale'));
        $data = Career::where('is_deleted', '0')->orderBy('department', 'asc')->orderBy('created_at', 'desc')->get();
        return view('pages.career', compact('data'));
    }
    public function show($id)
    {
        if (Session::get('locale') == "") {
            Session::puh('locale', 'en');
        }
        App::setLocale(Session::get('locale'));
        $data = Career::find($id);
        return view('pages.career-detail', compact('data'));
    }
}

resources/views/pages/admin/career/edit.blade.php
@extends('layouts.dashboard.template')

@section('title')
    <title>
        Roatex Admin | Career</title>
@endsection

@section('content')
    <meta name="_token" content="{{ csrf_token() }}">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Careers</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Careers</li>
                            <li class="breadcrumb-item active">Edit</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Edit Data Career</h3>
                            </div>
                            <div class="card-body">
                                <form action="update" id="form-career">
                                    @csrf
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="department">Departemen / Divisi (Inggris)</label>
                                                <input type="text" class="form-control" id="department" name="department"
                                                    placeholder="Enter department" value="{{ $data->department }}">
                                                <span id="error-department" class="hide error-text text-red"></span>
                                            </div>
                                            <div class="form-group">
                                                <label for="department">Departemen / Divisi (Indonesia)</label>
                                                <input type="text" class="form-control" id="department_ind"
                                                    name="department_ind" placeholder="Enter department"
                                                    value="{{ $data->department_ind }}">
                                                <span id="error-department_ind" class="hide error-text text-red"></span>
                                            </div>
                                            <div class="form-group">
                                                <label for="title">Posisi (Inggris)</label>
                                                <input type="text" class="form-control" id="title" name="title"
                                                    placeholder="Enter title" value="{{ $data->title }}">
                                                <span id="error-title" class="hide error-text text-red"></span>
                                            </div>
                                            <div class="form-group">
                                                <label for="title">Posisi (Indonesia)</label>
                                                <input type="text" class="form-control" id="title_ind" name="title_ind"
                                                    placeholder="Enter title" value="{{ $data->title_ind }}">
                                                <span id="error-title_ind" class="hide error-text text-red"></span>
                                            </div>
                                            <div class="form-group">
                                                <label for="desc">Deskripsi (Inggris)</label>
                                                <textarea name="desc" id="desc" cols="30" rows="10" placeholder="Enter Description"
                                                    class="form-control">{{ $data->desc }}</textarea>
                                                <span id="error-desc" class="hide error-text text-red"></span>
                                            </div>
                                            <div class="form-group">
                                                <label for="desc">Deskripsi (Indonesia)</label>
                                                <textarea name="desc_ind" id="desc_ind" cols="30" rows="10" placeholder="Enter Description"
                                                    class="form-control">{{ $data->desc_ind }}</textarea>
                                                <span id="error-desc_ind" class="hide error-text text-red"></span>
                                            </div>
                                            <div class="form-group">
                                                <label for="status">Status</label>
                                                <select name="status" id="status" class="form-control">
                                                    <option value="">-- Pilih --</option>
                                                    <option value="0" {{ $data->is_deleted == 0 ? 'selected' : '' }}>
                                                        Aktif</option>
                                                    <option value="1" {{ $data->is_deleted == 1 ? 'selected' : '' }}>
                                                        Non Aktif</option>
                                                </select>
                                                <span id="error-status" class="hide error-text text-red"></span>
                                            </div>
                                            <input type="hidden" name="id" id="id" value="{{ $data->id }}">
                                            <div class="form-group">
                                                <div class="float-right">
                                                    <div class="btn-group">
                                                        <a href="{{ route('admin.careers.index') }}"
                                                            class="btn btn-warning" style="color: white"><i
                                                                class="fa fa-arrow-alt-circle-left"></i>
                                                            Kembali
                                                        </a>
                                                        <button type="button" class="btn btn-primary"
                                                            id="submit-career">Simpan</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/pages/admin/career/index.blade.php
@extends('layouts.dashboard.template')

@section('title')
    <title>
        Roatex Admin | Careers</title>
@endsection

@section('content')
    <meta name="_token" content="{{ csrf_token() }}">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Careers</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Careers</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Data Careers</h3>
                                <div class="float-right">
                                    <button type="button" class="btn btn-primary d-flex align-items-center gap-2"
                                        data-toggle="modal" data-target="#mymodal">
                                        <i class="fa fa-plus-circle"></i>
                                        Tambah
                                    </button>
                                    <x-modal-input formID="submit-career" class="modal-xl">
                                        @slot('title')
                                            Tambah Karir
                                        @endslot
                                        @slot('form')
                                            <form action="store" id="form-career">
                                                @csrf
                                                <div class="row">
                                                    <div class="col-12">
                                                        <div class="form-group">
                                                            <label for="department">Departemen / Divisi (Inggris)</label>
                                                            <input type="text" class="form-control" id="department"
                                                                name="department" placeholder="Enter department">
                                                            <span id="error-department" class="hide error-text text-red"></span>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="department">Departemen / Divisi (Indonesia)</label>
                                                            <input type="text" class="form-control" id="department_ind"
                                                                name="department_ind" placeholder="Enter department">
                                                            <span id="error-department_ind" class="hide error-text text-red"></span>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="title">Posisi (Inggris)</label>
                                                            <input type="text" class="form-control" id="title"
                                                                name="title" placeholder="Enter title">
                                                            <span id="error-title" class="hide error-text text-red"></span>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="title">Posisi (Indonesia)</label>
                                                            <input type="text" class="form-control" id="title_ind"
                                                                name="title_ind" placeholder="Enter title">
                                                            <span id="error-title_ind" class="hide error-text text-red"></span>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="desc">Deskripsi (Inggris)</label>
                                                            <textarea name="desc" id="desc" cols="30" rows="10" placeholder="Enter Description"
                                                                class="form-control"></textarea>
                                                            <span id="error-desc" class="hide error-text text-red"></span>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="desc">Deskripsi (Indonesia)</label>
                                                            <textarea name="desc_ind" id="desc_ind" cols="30" rows="10" placeholder="Enter Description"
                                                                class="form-control"></textarea>
                                                            <span id="error-desc_ind" class="hide error-text text-red"></span>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="status">Status</label>
                                                            <select name="status" id="status" class="form-control">
                                                                <option value="">-- Pilih --</option>
                                                                <option value="1">Aktif</option>
                                                                <option value="0">Non Aktif</option>
                                                            </select>
                                                            <span id="error-status" class="hide error-text text-red"></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        @endslot
                                    </x-modal-input>
                                </div>
                            </div>
                            <div class="card-body">
                                <table id="datatables" class="table table-bordered table-hover table-responsive">
                                    <thead class="text-center" style="width: 100%">
                                        <tr>
                                            <th style="width: 3%">No</th>
                                            <th style="width: 10%">Departemen / Divisi (EN)</th>
                                            <th style="width: 10%">Departemen / Divisi (ID)</th>
                                            <th style="width: 25%">Posisi (EN)</th>
                                            <th style="width: 25%">Posisi (ID)</th>
                                            <th style="width: 25%">Deskripsi (EN)</th>
                                            <th style="width: 25%">Deskripsi (ID)</th>
                                            <th style="width: 10%">Dibuat Oleh</th>
                                            <th style="width: 5%">Status</th>
                                            <th style="width: 15%">Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody class="text-center">
                                        @foreach ($data as $item)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $item->department }}</td>
                                                <td>{{ $item->department_ind }}</td>
                                                <td>{{ $item->title }}</td>
                                                <td>{{ $item->title_ind }}</td>
                                                <td><span
                                                        style="display: -webkit-box;overflow: hidden;-webkit-line-clamp: 5;-webkit-box-orient: vertical;">{{ $item->desc }}</span>
                                                </td>
                                                <td><span
                                                        style="display: -webkit-box;overflow: hidden;-webkit-line-clamp: 5;-webkit-box-orient: vertical;">{{ $item->desc_ind }}</span>
                                                </td>
                                                <td>{{ $item->user }}</td>
                                                <td>
                                                    @if ($item->is_deleted == 0)
                                                        <span class="badge btn-success">Aktif</span>
                                                    @else
                                                        <span class="badge btn-danger">Non Aktif</span>
                                                    @endif
                                                </td>
                                                <td>
                                                    @if ($item->is_deleted == 0)
                                                        <div class="btn-group">
                                                            <a href="{{ route('admin.careers.edit', $item->id) }}"
                                                                class="btn btn-primary"><i class="fa fa-pencil-alt"></i>
                                                                Ubah </a>
                                                            <a href="javascript:void(0)" class="btn btn-danger"
                                                                data-id={{ $item->id }} data-action=1
                                                                data-aksi="onaktifkan" onclick="actionData(this)"><i
                                                                    class="fa fa-ban"></i>
                                                                Nonaktifkan </a>
                                                        </div>
                                                    @else
                                                        <div class="btn-group">
                                                            <a href="{{ route('admin.careers.edit', $item->id) }}"
                                                                class="btn btn-primary"><i class="fa fa-pencil-alt"></i>
                                                                Ubah </a>
                                                            <a href="javascrip:void(0)" class="btn btn-success"
                                                                data-id={{ $item->id }} data-action=0
                                                                data-aksi="aktifkan" onclick="actionData(this)"><i
                                                                    class="fa fa-ban"></i>
                                                                Aktifkan </a>
                                                        </div>
                                                    @endif
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection