routes/web.php
<?php

use App\Http\Controllers\Admin\CareerController as AdminCareerController;
use App\Http\Controllers\Admin\Content\AboutController;
use App\Http\Controllers\Admin\Content\HomeController;
use App\Http\Controllers\Admin\Content\SolutionController as ContentSolutionController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Home\HomepageController;
use App\Http\Controllers\Home\TechnologyController;
use App\Http\Controllers\Home\CareerController;
use App\Http\Controllers\Home\SolutionController;
use App\Http\Controllers\Home\NewsController;
use App\Http\Controllers\Home\AboutUsController;
use App\Http\Controllers\Home\ServicesController;

use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\NewsController as AdminNewsController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;

Route::get('/', [HomepageController::class, 'index'])->name('homepage');
Route::get('/lang/id', function () {
    Session::put('locale', 'id');
    App::setLocale('id');
    return back();
})->name('lang-id');

Route::get('/lang/en', function () {
    Session::put('locale', 'en');
    return back();
})->name('lang-en');

Route::get('/home/{id}', [HomepageController::class, 'show'])->name('homepage-show');
Route::post('/login', [LoginController::class, 'login'])->name('login-attempt');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

Route::get('/technology', [TechnologyController::class, 'index'])->name('tech-index');

Route::get('/aboutus', [AboutUsController::class, 'index'])->name('aboutus-index');

Route::get('/career', [CareerController::class, 'index'])->name('career-index');
Route::get('/career/{id}', [CareerController::class, 'show'])->name('career-show');

Route::get('/news', [NewsController::class, 'index'])->name('news-index');
Route::get('/news/{id}', [NewsController::class, 'show'])->name('news-show');

Route::get('/solution', [SolutionController::class, 'index'])->name('solution-index');

Route::get('/services', [ServicesController::class, 'index'])->name('services-index');

Route::get('/login', [LoginController::class, 'index'])->name('login-index');

Route::get('/dashboard', function () {
    return view('layouts.dashboard');
});


//admin
Route::prefix('/admin')->name('admin.')->middleware(['isUser'])->group(function () {
    Route::get(
        '/dashboard',
        function () {
            return view('pages.admin.dashboard');
        }
    )->name('dashboard');

    Route::prefix('/users')->name('users.')->group(
        function () {
            Route::get('/', [UserController::class, 'index'])->name('index');
            Route::post('/store', [UserController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [UserController::class, 'edit'])->name('edit');
            Route::post('/update', [UserController::class, 'update'])->name('update');
            Route::post('/action', [UserController::class, 'action'])->name('action');
        }
    );

    Route::prefix('/careers')->name('careers.')->group(
        function () {
            Route::get('/', [AdminCareerController::class, 'index'])->name('index');
            Route::post('/store', [AdminCareerController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [AdminCareerController::class, 'edit'])->name('edit');
            Route::post('/update', [AdminCareerController::class, 'update'])->name('update');
            Route::post('/action', [AdminCareerController::class, 'action'])->name('action');
        }
    );

    Route::prefix('/news')->name('news.')->group(
        function () {
            Route::get('/', [AdminNewsController::class, 'index'])->name('index');
            Route::post('/store', [AdminNewsController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [AdminNewsController::class, 'edit'])->name('edit');
            Route::post('/update', [AdminNewsController::class, 'update'])->name('update');
            Route::post('/action', [AdminNewsController::class, 'action'])->name('action');
        }
    );

    Route::prefix('/content')->name('content.')->group(
        function () {
            Route::prefix('/home')->name('home.')->group(
                function () {
                    Route::get('/', [HomeController::class, 'index'])->name('index');
                    Route::get('/edit/{id}', [HomeController::class, 'edit'])->name('edit');
                    Route::post('/update', [HomeController::class, 'update'])->name('update');
                }
            );
            Route::prefix('/about-us')->name('about.')->group(
                function () {
                    Route::get('/', [AboutController::class, 'index'])->name('index');
                    Route::get('/edit/{id}', [AboutController::class, 'edit'])->name('edit');
                    Route::post('/update', [AboutController::class, 'update'])->name('update');
                }
            );
            Route::prefix('/solution')->name('solution.')->group(
                function () {
                    Route::get('/', [ContentSolutionController::class, 'index'])->name('index');
                    Route::get('/edit/{id}', [ContentSolutionController::class, 'edit'])->name('edit');
                    Route::post('/update', [ContentSolutionController::class, 'update'])->name('update');
                }
            );
        }
    );
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_active',
        'user_inserted'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    public function index()
    {
        $data = User::all();
        return view('pages.admin.user.index', compact('data'));
    }
    public function store(Request $request)
    {
        $data = Validator::make(
            $request->all(),
            [
                'name' => ['required', 'string', 'max:255'],
                'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
                'password' => ['required', 'string', 'min:5'],
                'status' => ['required',],
            ]
        );

        if ($data->fails()) {
            $result = array('status' => 'failed', 'errors' => $data->errors());
        } else {
            User::create([
                'name' => $request->name,
                'email' => $request->email,
                'is_active' => $request->status,
                'user_inserted' => Auth::user()->name,
                'password' => Hash::make($request->password),
            ]);
            $result = array('status' => 'success');
        }
        echo json_encode($result);
    }

    public function edit(Request $request, $id)
    {
        $data = User::find($id);
        $data->password = '';
        return view('pages.admin.user.edit', compact('data'));
    }

    public function update(Request $request)
    {
        $data = Validator::make(
            $request->all(),
            [
                'name' => ['required', 'string', 'max:255'],
                'email' => ['required', 'string', 'email', 'max:255'],
                'status' => ['required',],
            ]
        );

        if ($data->fails()) {
            $result = array('status' => 'failed', 'errors' => $data->errors());
        } else {
            $user = User::find($request->id);
            if ($user->email != $request->email) {
                $data = Validator::make(
                    $request->all(),
                    [
                        'email' => ['unique:users']
                    ]
                );
                if ($data->fails()) {
                    $result = array('status' => 'failed', 'errors' => $data->errors());
                }
            }
            if ($request->password != null) {
                $data = Validator::make(
                    $request->all(),
                    [
                        'password' => ['required', 'string', 'min:5'],
                    ]
                );
                if ($data->fails()) {
                    $result = array('status' => 'failed', 'errors' => $data->errors());
                }
                $user->update([
                    'name' => $request->name,
                    'email' => $request->email,
                    'is_active' => $request->status,
                    'password' => Hash::make($request->password),
                ]);
            } else {
                $user->update([
                    'name' => $request->name,
                    'email' => $request->email,
                    'is_active' => $request->status,
                ]);
                $result = array('status' => 'success');
            }
        }
        echo json_encode($result);
    }

    public function action(Request $request)
    {
        $data = User::find($request->id);
        $data->is_active = intval($request->action);
        $data->save();
        $result = array('status' => 'success', 'data' => $data);
        echo json_encode($result);
    }
}

resources/views/pages/admin/user/edit.blade.php
@extends('layouts.dashboard.template')

@section('title')
    <title>
        Roatex Admin | Users</title>
@endsection

@section('content')
    <meta name="_token" content="{{ csrf_token() }}">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Users</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Users</li>
                            <li class="breadcrumb-item active">Edit</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Edit Data Users</h3>
                            </div>
                            <div class="card-body">
                                <form action="update" id="form-user">
                                    @csrf
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="name">Nama</label>
                                                <input type="text" class="form-control" id="name" name="name"
                                                    placeholder="Enter name" value="{{ $data->name }}" required>
                                                <span id="error-name" class="hide error-text text-red"></span>
                                            </div>
                                            <div class="form-group">
                                                <label for="email">Alamat Email</label>
                                                <input type="email" class="form-control" id="email" name="email"
                                                    placeholder="Enter email" value="{{ $data->email }}" required>
                                                <span id="error-email" class="hide error-text text-red"></span>
                                            </div>
                                            <div class="form-group">
                                                <label for="password">Password</label>
                                                <input type="password" class="form-control" id="password" name="password">
                                                <span id="error-password" class="hide error-text text-red"></span>
                                            </div>
                                            <div class="form-group">
                                                <label for="status">Status</label>
                                                <select name="status" id="status" class="form-control">
                                                    <option value="">-- Pilih --</option>
                                                    <option value="1" {{ $data->is_active == 1 ? 'selected' : '' }}>
                                                        Aktif</option>
                                                    <option value="0" {{ $data->is_active == 0 ? 'selected' : '' }}>Non
                                                        Aktif</option>
                                                </select>
                                                <span id="error-status" class="hide error-text text-red"></span>
                                            </div>
                                            <input type="hidden" name="id" id="id" value="{{ $data->id }}">
                                            <div class="form-group">
                                                <div class="float-right">
                                                    <div class="btn-group">
                                                        <a href="{{ route('admin.users.index') }}" class="btn btn-warning"
                                                            style="color: white"><i class="fa fa-arrow-alt-circle-left"></i>
                                                            Kembali
                                                        </a>
                                                        <button type="button" class="btn btn-primary"
                                                            id="submit-user">Simpan</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/pages/admin/user/index.blade.php
@extends('layouts.dashboard.template')

@section('title')
    <title>
        Roatex Admin | Users</title>
@endsection

@section('content')
    <meta name="_token" content="{{ csrf_token() }}">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Users</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Users</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Data Users</h3>
                                <div class="float-right">
                                    <button type="button" class="btn btn-primary d-flex align-items-center gap-2"
                                        data-toggle="modal" data-target="#mymodal">
                                        <i class="fa fa-plus-circle"></i>
                                        Tambah
                                    </button>
                                    <x-modal-input formID="submit-user">
                                        @slot('title')
                                            Tambah User
                                        @endslot
                                        @slot('form')
                                            <form action="store" id="form-user">
                                                @csrf
                                                <div class="row">
                                                    <div class="col-12">
                                                        <div class="form-group">
                                                            <label for="name">Nama</label>
                                                            <input type="text" class="form-control" id="name"
                                                                name="name" placeholder="Enter name">
                                                            <span id="error-name" class="hide error-text text-red"></span>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="email">Alamat Email</label>
                                                            <input type="email" class="form-control" id="email"
                                                                name="email" placeholder="Enter email">
                                                            <span id="error-email" class="hide error-text text-red"></span>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="password">Password</label>
                                                            <input type="password" class="form-control" id="password"
                                                                name="password" placeholder="Enter password">
                                                            <span id="error-password" class="hide error-text text-red"></span>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="status">Status</label>
                                                            <select name="status" id="status" class="form-control">
                                                                <option value="">-- Pilih --</option>
                                                                <option value="1">Aktif</option>
                                                                <option value="0">Non Aktif</option>
                                                            </select>
                                                            <span id="error-status" class="hide error-text text-red"></span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        @endslot
                                    </x-modal-input>
                                </div>
                            </div>
                            <div class="card-body">
                                <table id="datatables" class="table table-bordered table-hover table-responsive">
                                    <thead class="text-center" style="width: 100%">
                                        <tr>
                                            <th style="width: 5%">No</th>
                                            <th style="width: 25%">Nama</th>
                                            <th style="width: 25%">Email</th>
                                            <th style="width: 25%">Status</th>
                                            <th style="width: 25%">Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody class="text-center">
                                        @foreach ($data as $item)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $item->name }}</td>
                                                <td>{{ $item->email }}</td>
                                                <td>
                                                    @if ($item->is_active == 1)
                                                        <span class="badge btn-success">Aktif</span>
                                                    @else
                                                        <span class="badge btn-danger">Non Aktif</span>
                                                    @endif
                                                </td>
                                                <td>
                                                    @if ($item->is_active == 1)
                                                        <div class="btn-group">
                                                            <a href="{{ route('admin.users.edit', $item->id) }}"
                                                                class="btn btn-primary"><i class="fa fa-pencil-alt"></i>
                                                                Ubah </a>
                                                            <a href="javascript:void(0)" class="btn btn-danger"
                                                                data-id={{ $item->id }} data-action=0
                                                                data-aksi="nonaktifkan user ini"
                                                                onclick="actionData(this)"><i class="fa fa-ban"></i>
                                                                Nonaktifkan </a>
                                                        </div>
                                                    @else
                                                        <div class="btn-group">
                                                            <a href="{{ route('admin.users.edit', $item->id) }}"
                                                                class="btn btn-primary"><i class="fa fa-pencil-alt"></i>
                                                                Ubah </a>
                                                            <a href="javascrip:void(0)" class="btn btn-success"
                                                                data-id={{ $item->id }} data-action=1
                                                                data-aksi="aktifkan user ini" onclick="actionData(this)"><i
                                                                    class="fa fa-ban"></i>
                                                                Aktifkan </a>
                                                        </div>
                                                    @endif
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection